packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@img/sharp-linux-x64"
  - "@img/sharp-linux-arm64"
  - "@img/sharp-darwin-arm64"
  - "@img/sharp-darwin-x64"
